# Site settings
name: LaPlataJS

email: your-email@domain.com

#url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: laplatajs
github_username:  laplatajs
facebook_group: laplatajs
gplus: 107431169588797814323

# Build settings
markdown: kramdown
